---
sidebar: sidebar 
permalink: trident-docker/volume-driver-options.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume, driver options, ontap, element volumes, cvs, cloud volumes service on gcp, azure netapp files 
summary: 각 스토리지 드라이버에는 다양한 옵션이 있으며, 볼륨 생성 시 이를 지정하여 결과를 사용자 지정할 수 있습니다. 구성된 스토리지 시스템에 적용되는 옵션은 아래를 참조하십시오. 
---
= 드라이버별 볼륨 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


각 스토리지 드라이버에는 다양한 옵션이 있으며, 볼륨 생성 시 이를 지정하여 결과를 사용자 지정할 수 있습니다. 구성된 스토리지 시스템에 적용되는 옵션은 아래를 참조하십시오.

볼륨 생성 작업 중에 이러한 옵션을 사용하는 것은 간단합니다. 을 사용하여 옵션과 값을 제공합니다 `-o` CLI 작업 중 operator이다. 이러한 값은 JSON 구성 파일의 모든 등가 값을 재정의합니다.



== ONTAP 볼륨 옵션

NFS 및 iSCSI에 대한 볼륨 생성 옵션은 다음과 같습니다.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `size`  a| 
볼륨의 크기는 기본적으로 1GiB로 설정됩니다.



| `spaceReserve`  a| 
볼륨을 씬 또는 일반 프로비저닝합니다. 기본값은 Thin 입니다. 유효한 값은 입니다 `none` (씬 프로비저닝됨) 및 을 누릅니다 `volume` (일반 프로비저닝).



| `snapshotPolicy`  a| 
그러면 스냅샷 정책이 원하는 값으로 설정됩니다. 기본값은 입니다 `none`즉, 볼륨에 대해 스냅샷이 자동으로 생성되지 않습니다. 스토리지 관리자가 수정하지 않는 한, "default"라는 정책이 모든 ONTAP 시스템에 존재하며, 이 정책은 6시간, 2일, 2주 스냅샷을 생성하고 유지합니다. 스냅샷에 보존된 데이터는 로 이동하여 복구할 수 있습니다 `.snapshot` 디렉토리에 저장됩니다.



| `snapshotReserve`  a| 
이렇게 하면 스냅숏 예비 공간이 원하는 비율로 설정됩니다. 기본값은 값이 없습니다. 즉, snapshotPolicy를 선택한 경우 ONTAP가 snapshotReserve(일반적으로 5%)를 선택하거나 snapshotPolicy가 none인 경우 0%를 선택합니다. 모든 ONTAP 백엔드에 대한 구성 파일에서 기본 snapshotReserve 값을 설정할 수 있으며 ONTAP-NAS-이코노미 를 제외한 모든 ONTAP 백엔드에 대한 볼륨 생성 옵션으로 사용할 수 있습니다.



| `splitOnClone`  a| 
볼륨을 클론 생성할 때 ONTAP가 상위 클론에서 즉시 클론을 분할합니다. 기본값은 입니다 `false`. 볼륨을 클론 복제하는 사용 사례에는 스토리지 효율성을 높일 기회가 없을 것 같기 때문에 생성 즉시 클론을 상위 볼륨에서 분리하는 것이 가장 좋습니다. 예를 들어 빈 데이터베이스를 복제하면 많은 시간을 절약할 수 있지만 스토리지 절감 효과는 거의 없으므로 즉시 클론을 분리하는 것이 좋습니다.



| `encryption`  a| 
새 볼륨에 NVE(NetApp Volume Encryption)를 활성화합니다. 기본값은 입니다 `false`. 이 옵션을 사용하려면 NVE 라이센스가 클러스터에서 활성화되어 있어야 합니다.

백엔드에서 NAE가 활성화된 경우 Astra Trident에 프로비저닝된 모든 볼륨은 NAE가 활성화됩니다.

자세한 내용은 다음을 참조하십시오. link:../trident-reco/security-reco.html["Astra Trident가 NVE 및 NAE와 연동되는 방식"].



| `tieringPolicy`  a| 
볼륨에 사용할 계층화 정책을 설정합니다. 비활성(콜드) 상태일 때 데이터를 클라우드 계층으로 이동할지 결정합니다.

|===
다음 추가 옵션은 NFS * 에만 적용됩니다 *.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `unixPermissions`  a| 
볼륨 자체에 대한 권한 집합을 제어합니다. 기본적으로 사용 권한은 로 설정됩니다 ``---rwxr-xr-x`, 또는 숫자 표기 0755, 및 `root` 소유자가 됩니다. 텍스트 또는 숫자 형식이 작동합니다.



| `snapshotDir`  a| 
를 로 설정합니다 `true` 가 을(를) 만듭니다 `.snapshot` 볼륨을 액세스하는 클라이언트가 볼 수 있는 디렉토리입니다. 기본값은 입니다 `false`이는 의 가시성을 의미합니다 `.snapshot` 디렉토리는 기본적으로 사용되지 않습니다. 예를 들어, 공식 MySQL 이미지와 같은 일부 이미지는 에서 예상대로 작동하지 않습니다 `.snapshot` 디렉토리가 표시됩니다.



| `exportPolicy`  a| 
볼륨에 사용할 엑스포트 정책을 설정합니다. 기본값은 입니다 `default`.



| `securityStyle`  a| 
볼륨에 액세스하는 데 사용할 보안 스타일을 설정합니다. 기본값은 입니다 `unix`. 유효한 값은 입니다 `unix` 및 `mixed`.

|===
다음 추가 옵션은 iSCSI * 에만 적용됩니다 *.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `fileSystemType` | iSCSI 볼륨을 포맷하는 데 사용되는 파일 시스템을 설정합니다. 기본값은 입니다 `ext4`. 유효한 값은 입니다 `ext3`, `ext4`, 및 `xfs`. 


| `spaceAllocation` | 를 로 설정합니다 `false` 에서는 LUN의 공간 할당 기능을 해제합니다. 기본값은 입니다 `true`즉, ONTAP는 볼륨에 공간이 부족하고 볼륨의 LUN이 쓰기를 허용할 수 없을 때 호스트에 알립니다. 또한 이 옵션을 사용하면 호스트가 데이터를 삭제할 때 ONTAP에서 자동으로 공간을 재확보할 수 있습니다. 
|===


=== 예

아래 예를 참조하십시오.

* 10GiB 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=10G -o encryption=true
----
* 스냅샷을 사용하여 100GiB 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=100G -o snapshotPolicy=default -o snapshotReserve=10
----
* setuid 비트가 설정된 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name demo -o unixPermissions=4755
----


최소 볼륨 크기는 20MiB입니다.

스냅숏 예비 공간이 지정되지 않은 경우 스냅숏 정책이 입니다 `none`, Trident는 0%의 스냅숏 예비 공간을 사용합니다.

* 스냅숏 정책이 없고 스냅숏 예비 공간이 없는 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none
----
* 스냅샷 정책이 없는 볼륨 및 10%의 사용자 지정 스냅숏 예비 공간을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=none --opt snapshotReserve=10
----
* 스냅샷 정책 및 10%의 사용자 지정 스냅숏 예비 공간이 있는 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy --opt snapshotReserve=10
----
* 스냅샷 정책을 사용하여 볼륨을 생성하고 ONTAP의 기본 스냅샷 예약 공간(일반적으로 5%)을 적용합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt snapshotPolicy=myPolicy
----




== Element 소프트웨어 볼륨 옵션

Element 소프트웨어 옵션은 볼륨과 연관된 서비스 품질(QoS) 정책의 크기 및 크기를 표시합니다. 볼륨이 생성되면 볼륨을 사용하여 연결된 QoS 정책을 지정합니다 `-o type=service_level` 명칭.

Element 드라이버로 QoS 서비스 수준을 정의하는 첫 번째 단계는 하나 이상의 유형을 생성하고 구성 파일의 이름과 연결된 최소, 최대 및 버스트 IOPS를 지정하는 것입니다.

기타 Element 소프트웨어 볼륨 생성 옵션에는 다음이 포함됩니다.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `size`  a| 
볼륨 크기, 기본값 1GiB 또는 구성 항목... "기본값":{"크기":"5G"}.



| `blocksize`  a| 
512 또는 4096 중 하나를 사용합니다. 기본값은 512 또는 구성 항목 DefaultBlockSize 입니다.

|===


=== 예

QoS 정의가 포함된 다음 샘플 구성 파일을 참조하십시오.

[listing]
----
{
    "...": "..."
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----
위 구성에서는 Bronze, Silver, Gold의 세 가지 정책 정의가 있습니다. 이러한 이름은 임의로 지정됩니다.

* 10GiB 골드 볼륨 생성:
+
[listing]
----
docker volume create -d solidfire --name sfGold -o type=Gold -o size=10G
----
* 100GiB Bronze 볼륨 생성:
+
[listing]
----
docker volume create -d solidfire --name sfBronze -o type=Bronze -o size=100G
----




== GCP 볼륨 옵션에 대한 CV

GCP 드라이버에서 CVS에 대한 볼륨 생성 옵션은 다음과 같습니다.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `size`  a| 
볼륨 크기는 CVS - 성능 볼륨의 경우 기본적으로 100GiB, CVS 볼륨의 경우 300GiB입니다.



| `serviceLevel`  a| 
볼륨의 CVS 서비스 수준은 기본적으로 표준입니다. 유효한 값은 표준, 프리미엄 및 극단입니다.



| `snapshotReserve`  a| 
이렇게 하면 스냅숏 예비 공간이 원하는 비율로 설정됩니다. 기본값은 no 값이며, 이는 CVS에서 스냅숏 예비 공간(일반적으로 0%)을 선택한다는 의미입니다.

|===


=== 예

* 2TiB 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=2T
----
* 5TiB 프리미엄 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=5T -o serviceLevel=premium
----


CVS 성능 볼륨의 경우 최소 볼륨 크기는 100GiB, CVS 볼륨의 경우 300GiB입니다.



== Azure NetApp Files 볼륨 옵션

Azure NetApp Files 드라이버에 대한 볼륨 생성 옵션은 다음과 같습니다.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


| `size`  a| 
볼륨 크기는 기본적으로 100GB입니다.

|===


=== 예

* 200GiB 볼륨 생성:
+
[listing]
----
docker volume create -d netapp --name demo -o size=200G
----


최소 볼륨 크기는 100GB입니다.
