---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp은 제품과 서비스를 지속적으로 개선 및 개선하고 있습니다. 다음은 최신 버전의 Astra Trident에 포함된 최신 기능, 개선 사항 및 버그 수정 사항입니다. 
---
= 릴리즈 노트
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


릴리즈 노트 최신 버전의 Astra Trident에 새로운 기능, 개선 사항 및 버그 수정 사항에 대한 정보를 제공합니다.


WARNING: 를 클릭합니다 `tridentctl` 설치 프로그램 zip 파일에 제공된 Linux용 바이너리는 테스트되고 지원되는 버전입니다. 에 유의하십시오 `macos` 에 제공된 바이너리 `/extras` zip 파일의 일부가 테스트되지 않았거나 지원되지 않습니다.



== 22.07의 새로운 기능



=== 수정

** Kubernetes**

* Hrom 또는 Trident 연산자를 사용하여 Trident를 구성할 때 노드 선택기에 대한 부울 및 숫자 값을 처리하는 문제가 해결되었습니다. (link:https://github.com/NetApp/trident/issues/700["GitHub 문제 #700"^])
* CHAP가 아닌 경로에서 발생하는 오류를 처리하는 문제를 수정함으로써 kubelet이 실패한 경우 다시 시도합니다. link:https://github.com/NetApp/trident/issues/736["GitHub 문제 #736"^])




=== 향상된 기능

* k8s.gcr.io에서 registry.k8s.io로 CSI 이미지의 기본 레지스트리로 전환합니다
* ONTAP-SAN 볼륨은 이제 노드별 igroup을 사용하며 해당 노드에 능동적으로 게시되는 LUN만 igroup에 매핑하여 보안 상태를 향상합니다. Trident가 활성 워크로드에 영향을 주지 않고 안전하게 수행할 수 있다고 판단하면 기존 볼륨이 새로운 igroup 체계로 자동으로 전환됩니다.
* Trident 설치에 리소스 할당량을 포함함으로써 PriorityClass 소비가 기본적으로 제한될 때 Trident DemonSet이 예약되도록 합니다.
* ANF 드라이버에 네트워크 기능에 대한 지원이 추가되었습니다. (link:https://github.com/NetApp/trident/issues/717["GitHub 문제 #717"^])
* ONTAP 드라이버에 기술 미리 보기 자동 MetroCluster 전환 감지 기능이 추가되었습니다. (link:https://github.com/NetApp/trident/issues/228["GitHub 문제 #228"^])




=== 사용 중단

* ** Kubernetes:** 최소 지원 Kubernetes를 1.19로 업데이트했습니다.
* 백엔드 구성은 더 이상 단일 구성에서 여러 인증 유형을 사용할 수 없습니다.




=== 제거

* AWS CVS 드라이버(22.04 이후 더 이상 사용되지 않음)가 제거되었습니다.
* 쿠버네티스
+
** 노드 포드에 불필요한 SYS_ADMIN 기능이 제거되었습니다.
** 노드 준비 작업을 간단한 호스트 정보로 줄이고 활성 서비스 검색을 통해 작업 노드에서 NFS/iSCSI 서비스를 사용할 수 있다는 최선의 확인 작업을 수행할 수 있습니다.






=== 문서화

새로운 소식 link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["POD 보안 표준"] (PSS) 섹션에 설치 시 Astra Trident에서 활성화한 상세 권한이 추가되었습니다.



== 22.04의 변경

NetApp은 제품과 서비스를 지속적으로 개선 및 개선하고 있습니다. Astra Trident의 최신 기능 몇 가지를 소개합니다. 이전 릴리스는 를 참조하십시오 https://docs.netapp.com/us-en/trident/earlier-versions.html["이전 버전의 문서"].


IMPORTANT: 이전 Trident 릴리즈에서 업그레이드하고 Azure NetApp Files를 사용하는 경우, 를 참조하십시오 ``location`` 구성 매개 변수는 이제 필수 싱글톤 필드입니다.



=== 수정

* iSCSI 이니시에이터 이름의 구문 분석 기능이 향상되었습니다. (link:https://github.com/NetApp/trident/issues/681["GitHub 문제 #681"^])
* CSI 스토리지 클래스 매개 변수가 허용되지 않는 문제를 해결했습니다. (link:https://github.com/NetApp/trident/issues/598["GitHub 문제 #598"^])
* Trident CRD에서 중복 키 선언을 수정했습니다. (link:https://github.com/NetApp/trident/issues/671["GitHub 문제 #671"^])
* 부정확한 CSI 스냅샷 로그를 수정했습니다. (link:https://github.com/NetApp/trident/issues/629["GitHub 문제 #629"^]))
* 삭제된 노드에서 볼륨 게시를 취소하는 문제 해결 (link:https://github.com/NetApp/trident/issues/691["GitHub 문제 #691"^])
* 블록 디바이스에서 파일 시스템 불일치를 처리하는 기능이 추가되었습니다. (link:https://github.com/NetApp/trident/issues/656["GitHub 문제 #656"^])
* 를 설정할 때 자동 지원 이미지를 가져오는 문제가 해결되었습니다 `imageRegistry` 설치 중 플래그. (link:https://github.com/NetApp/trident/issues/715["GitHub 문제 #715"^])
* ANF 드라이버가 여러 내보내기 규칙을 사용하여 볼륨을 클론하지 못한 문제 해결




=== 향상된 기능

* 이제 Trident의 보안 끝점에 대한 인바운드 연결에는 TLS 1.3 이상이 필요합니다. (link:https://github.com/NetApp/trident/issues/698["GitHub 문제 #698"^])
* 이제 Trident는 보안 엔드포인트의 응답에 HSTS 헤더를 추가합니다.
* 이제 Trident는 Azure NetApp Files UNIX 사용 권한 기능을 자동으로 활성화하려고 시도합니다.
* * Kubernetes *: Trident가 이제 시스템 노드 크리티컬 우선 순위 클래스에서 실행됩니다. (link:https://github.com/NetApp/trident/issues/694["GitHub 문제 #694"^])




=== 제거

E-Series 드라이버(20.07 이후 비활성화됨)가 제거되었습니다.



== 22.01.1의 변경 사항



=== 수정

* 삭제된 노드에서 볼륨 게시를 취소하는 문제 해결 (link:https://github.com/NetApp/trident/issues/691["GitHub 문제 #691"])
* ONTAP API 응답에서 공간 집계에 대한 nil 필드에 액세스할 때 패닉이 수정되었습니다.




== 22.01.0의 변경 사항



=== 수정

* * Kubernetes: * 대규모 클러스터의 노드 등록 백오프 재시도 시간을 늘립니다.
* 동일한 이름의 여러 리소스가 Azure-NetApp-files 드라이버를 혼동할 수 있는 문제 해결
* ONTAP SAN IPv6 데이터 LIF는 이제 대괄호와 함께 지정된 경우 작동합니다.
* 이미 가져온 볼륨을 가져오려고 하면 PVC가 보류 상태로 남겨둔 EOF가 반환되는 문제가 해결되었습니다. (link:https://github.com/NetApp/trident/issues/489["GitHub 문제 #489"])
* SolidFire 볼륨에 32개 이상의 스냅샷을 생성할 때 Astra Trident 성능이 느려지는 문제를 해결했습니다.
* SHA-1을 SSL 인증서 생성에서 SHA-256으로 교체했습니다.
* 중복된 리소스 이름을 허용하고 작업을 단일 위치로 제한하도록 ANF 드라이버를 수정했습니다.
* 중복된 리소스 이름을 허용하고 작업을 단일 위치로 제한하도록 ANF 드라이버를 수정했습니다.




=== 향상된 기능

* Kubernetes의 향상된 기능:
+
** Kubernetes 1.23 지원 추가.
** Trident Operator 또는 Hrom을 통해 설치된 Trident Pod에 대한 예약 옵션을 추가합니다. (link:https://github.com/NetApp/trident/issues/651["GitHub 문제 #651"^])


* GCP 드라이버에서 지역 간 볼륨을 허용합니다. (link:https://github.com/NetApp/trident/issues/633["GitHub 문제 #633"^])
* ANF 볼륨에 'unixPermissions' 옵션에 대한 지원이 추가되었습니다. (link:https://github.com/NetApp/trident/issues/666["GitHub 문제 #666"^])




=== 사용 중단

Trident REST 인터페이스는 127.0.0.1 또는 [::1] 주소에서만 수신 및 제공할 수 있습니다



== 21.10.1 변경


WARNING: v21.10.0 릴리즈에는 노드를 제거한 다음 Kubernetes 클러스터에 다시 추가할 때 Trident 컨트롤러를 CrashLoopBackOff 상태로 전환할 수 있는 문제가 있습니다. 이 문제는 v21.10.1(GitHub 문제 669)에서 해결되었습니다.



=== 수정

* GCP CVS 백엔드에서 볼륨을 가져올 때 잠재적인 경쟁 조건이 수정되어 가져오지 못했습니다.
* 노드를 제거할 때 Trident 컨트롤러를 CrashLoopBackOff 상태로 전환할 수 있는 문제를 해결한 다음 Kubernetes 클러스터(GitHub 문제 669)에 다시 추가되었습니다.
* SVM 이름이 지정되지 않은 경우 SVM이 더 이상 검색되지 않는 문제 해결(GitHub 문제 612)




== 21.10.0 변경



=== 수정

* XFS 볼륨의 클론을 소스 볼륨과 동일한 노드에 마운트할 수 없는 문제(GitHub 문제 514)가 해결되었습니다.
* Astra Trident에서 종료 시 심각한 오류를 기록한 문제 해결(GitHub 문제 597)
* Kubernetes 관련 수정 사항:
+
** 에서 스냅샷을 생성할 때 볼륨의 사용된 공간을 최소 restoreSize로 반환합니다 `ontap-nas` 및 `ontap-nas-flexgroup` 드라이버(GitHub 문제 645).
** 문제 해결 위치 `Failed to expand filesystem` 볼륨 크기 조정 후 오류가 기록되었습니다(GitHub 문제 560).
** 포드가 끼일 수 있는 문제 해결 `Terminating` State(GitHub 문제 572):
** 에서 케이스를 수정했습니다 `ontap-san-economy` FlexVol에 스냅샷 LUN이 가득 찼을 수 있습니다(GitHub 문제 533).
** 다른 이미지의 사용자 지정 YAML 설치 프로그램 문제 해결(GitHub 문제 613)
** 스냅샷 크기 계산 수정(GitHub 문제 611)
** 모든 Astra Trident 설치 관리자가 일반 Kubernetes를 OpenShift로 식별할 수 있는 문제 해결(GitHub 문제 639)
** Kubernetes API 서버에 연결할 수 없는 경우 조정을 중지하도록 Trident 연산자를 수정했습니다(GitHub 문제 599).






=== 향상된 기능

* 에 대한 지원이 추가되었습니다 `unixPermissions` GCP-CVS 성능 볼륨 옵션.
* 600GiB~1TiB 범위의 GCP에서 확장성 최적화 CVS 볼륨 지원 추가
* Kubernetes 관련 개선사항:
+
** Kubernetes 1.22에 대한 지원이 추가되었습니다.
** Trident 운영자 및 제어 차트를 Kubernetes 1.22(GitHub 문제 628)와 함께 사용할 수 있도록 했습니다.
** 에 운영자 이미지가 추가되었습니다 `tridentctl` images 명령(GitHub 문제 570).






=== 실험적인 개선

* 에서 볼륨 복제에 대한 지원이 추가되었습니다 `ontap-san` 드라이버.
* 에 대한 * 기술 미리보기 * REST 지원 추가 `ontap-nas-flexgroup`, `ontap-san`, 및 `ontap-nas-economy` 드라이버.




== 알려진 문제

알려진 문제점은 제품을 성공적으로 사용하지 못하게 만들 수 있는 문제를 식별합니다.

* Astra Trident가 이제 공란을 적용합니다 `fsType` (`fsType=""`)이 없는 볼륨의 경우 `fsType` StorageClass에 지정됩니다. Kubernetes 1.17 이상으로 작업할 경우 Trident는 공백을 제공할 수 있도록 지원합니다 `fsType` NFS 볼륨용. iSCSI 볼륨의 경우 를 설정해야 합니다 `fsType` 를 적용할 때 StorageClass에 대해 `fsGroup` 보안 컨텍스트 사용.
* 여러 Astra Trident 인스턴스에서 백엔드를 사용할 경우 각 백엔드 구성 파일은 서로 달라야 합니다 `storagePrefix` ONTAP 백엔드에 대한 값이거나 다른 값을 사용합니다 `TenantName` SolidFire 백엔드의 경우. Astra Trident는 Astra Trident의 다른 인스턴스가 생성한 볼륨을 감지할 수 없습니다. Astra Trident가 볼륨 생성을 idemptent 작업으로 처리하므로 ONTAP 또는 SolidFire 백엔드에서 기존 볼륨을 생성하려고 하면 성공합니다. If(경우 `storagePrefix` 또는 `TenantName` 서로 다를 수 없습니다. 동일한 백엔드에서 생성된 볼륨의 이름 충돌이 있을 수 있습니다.
* Astra Trident 설치 시(사용 `tridentctl` 또는 Trident Operator)를 사용하여 사용할 수 있습니다 `tridentctl` Astra Trident를 관리하려면 을(를) 확인해야 합니다 `KUBECONFIG` 환경 변수가 설정되었습니다. 이는 Kubernetes 클러스터를 나타내는 데 필요합니다 `tridentctl` 에 대해 작업해야 합니다. 여러 Kubernetes 환경을 사용할 때는 가 반드시 에 적합해야 합니다 `KUBECONFIG` 파일을 정확하게 소싱합니다.
* iSCSI PVS에 대해 온라인 공간 재확보를 수행하려면 작업자 노드의 기본 OS에 볼륨에 마운트 옵션을 전달해야 할 수 있습니다. 이 내용은 가 필요한 RHEL/RedHat CoreOS 인스턴스에 적용됩니다 `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["마운트 옵션"^]에 mountmounted 폐기 옵션이 포함되어 있는지 확인합니다[`StorageClass`^ ] 를 클릭하여 온라인 블록 버기를 지원합니다.
* Kubernetes 클러스터당 Astra Trident 인스턴스가 두 개 이상 있는 경우, Astra Trident가 다른 인스턴스와 통신할 수 없고 자신이 생성한 다른 볼륨을 검색할 수 없기 때문에 클러스터 내에서 둘 이상의 인스턴스가 실행될 경우 예기치 않거나 잘못된 동작이 발생합니다. Kubernetes 클러스터당 하나의 Astra Trident 인스턴스만 있어야 합니다.
* Astra Trident 기반인 경우 `StorageClass` Astra Trident가 오프라인인 동안 Kubernetes에서 객체가 삭제되며, Astra Trident는 온라인 상태로 돌아올 때 데이터베이스에서 해당 스토리지 클래스를 제거하지 않습니다. 를 사용하여 이러한 스토리지 클래스를 삭제해야 합니다 `tridentctl` 또는 REST API를 선택합니다.
* 사용자가 해당 PVC를 삭제하기 전에 Astra Trident가 프로비저닝한 PV를 삭제하는 경우 Astra Trident는 백업 볼륨을 자동으로 삭제하지 않습니다. 를 통해 볼륨을 제거해야 합니다 `tridentctl` 또는 REST API를 선택합니다.
* FlexGroup은 애그리게이트 세트가 각 프로비저닝 요청에서 고유하지 않으면 한 번에 둘 이상의 ONTAP를 동시에 프로비저닝할 수 없습니다.
* IPv6를 통해 Astra Trident를 사용할 때는 을 지정해야 합니다 `managementLIF` 및 `dataLIF` 백엔드 정의에서 대괄호로 묶습니다. 예를 들면, 다음과 같습니다. ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``.
* 를 사용하는 경우 `solidfire-san` OpenShift 4.5를 사용하는 드라이버 기본 작업자 노드가 CHAP 인증 알고리즘으로 MD5를 사용하는지 확인합니다.




== 자세한 내용을 확인하십시오

* https://github.com/NetApp/trident["Astra Trident GitHub를 참조하십시오"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident 블로그"^]

