---
settings:
  name: Astra Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    langs: us-en,ja-jp,zh-cn
sidebar:
  entries:
    - title: Astra Trident documentation
      url: /index.html
    - title: Release notes
      url: /trident-rn.html
    - section: trident-concepts
    - section: trident-get-started
    - section: trident-managing-k8s
    - section: trident-use
    - section: trident-docker
    - title: FAQs
      url: /faq.html
    - title: Support
      url: /get-help.html
    - title: Troubleshooting
      url: /troubleshooting.html
    - section: trident-reco
    - section: trident-reference
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal.html
product-family:
  name: Trident
  repo: astra-family