---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm 
summary: 'Trident 운영자나 를 사용하여 Astra Trident를 배포할 수 있습니다 `tridentctl`.' 
---
= 구축 개요
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Trident 운영자나 를 사용하여 Astra Trident를 배포할 수 있습니다 `tridentctl`.


NOTE: 22.04 릴리즈부터는 Astra Trident가 설치될 때마다 AES 키가 더 이상 다시 생성되지 않습니다. 이 릴리즈를 통해 Astra Trident는 설치 전반에 걸쳐 유지되는 새로운 비밀 객체를 설치합니다. 즉, `tridentctl` 22.04에서는 Trident의 이전 버전을 제거할 수 있지만 이전 버전에서는 22.04 설치를 제거할 수 없습니다.



== Kubernetes 1.25에 대한 중요 정보

Kubernetes 1.25는 Astra Trident 22.10에서 지원됩니다. Kubernetes 1.25로 업그레이드하기 전에 Astra Trident 22.10으로 업그레이드해야 합니다.



== 배포 방법을 선택합니다

사용할 배포 방법을 결정하려면 다음 사항을 고려하십시오.



=== Trident 연산자를 사용해야 하는 이유는 무엇입니까?

를 클릭합니다 link:kubernetes-deploy-operator.html["Trident 운영자"^] Astra Trident 리소스를 동적으로 관리하고 설정 단계를 자동화하는 훌륭한 방법입니다. 몇 가지 전제 조건이 충족되어야 합니다. 을 참조하십시오 link:requirements.html["설명합니다"^].

Trident 운영자는 아래에 설명된 여러 가지 이점을 제공합니다.



==== 자동 복구 기능

Astra Trident 설치를 모니터링하고 구축이 삭제되거나 실수로 수정된 경우와 같은 문제를 해결하기 위한 조치를 적극적으로 취할 수 있습니다. 운용자가 배치로 설정된 경우, a `trident-operator-<generated-id>` POD가 생성됩니다. 이 포드는 을(를) 연결합니다 `TridentOrchestrator` Astra Trident가 설치된 CR을 사용하면 항상 한 번만 활성화되도록 할 수 있습니다 `TridentOrchestrator`. 즉, 운영자는 클러스터에 Astra Trident 인스턴스가 하나만 있고 설정을 제어하여 설치가 매우 강력한지 확인합니다. 설치 변경(예: 배포 또는 노드 반점 삭제)이 수행되면 운영자가 이를 식별하고 개별적으로 수정합니다.



==== 기존 설치에 대한 손쉬운 업데이트

기존 배포를 운영자로 쉽게 업데이트할 수 있습니다. 를 편집하기만 하면 됩니다 `TridentOrchestrator` CR을 사용하여 설치를 업데이트합니다. 예를 들어, Astra Trident를 활성화하여 디버그 로그를 생성해야 하는 시나리오를 생각해 보십시오.

이렇게 하려면 에 패치를 적용합니다 `TridentOrchestrator` 를 눌러 설정합니다 `spec.debug` 를 선택합니다 `true`:

[listing]
----
kubectl patch torc <trident-orchestrator-name> -n trident --type=merge -p '{"spec":{"debug":true}}'
----
이후 `TridentOrchestrator` 이 업데이트되면 운영자가 업데이트를 처리하고 기존 설치를 패치합니다. 이렇게 하면 새 포드가 생성되어 설치를 적절하게 수정할 수 있습니다.



==== Kubernetes 업그레이드 자동 처리

클러스터의 Kubernetes 버전이 지원되는 버전으로 업그레이드되면 운영자는 기존 Astra Trident 설치를 자동으로 업데이트하고 Kubernetes 버전 요구사항을 충족하도록 변경합니다.


NOTE: 클러스터가 지원되지 않는 버전으로 업그레이드되면 운영자는 Astra Trident를 설치할 수 없습니다. Astra Trident가 운영자와 함께 이미 설치된 경우 Astra Trident가 지원되지 않는 Kubernetes 버전에 설치되었음을 나타내는 경고가 표시됩니다.



==== Cloud Manager를 사용하여 Kubernetes 클러스터를 관리합니다

와 함께 link:https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html["Cloud Manager를 사용하는 Astra Trident"^]Astra Trident의 최신 버전으로 업그레이드하고, 스토리지 클래스를 추가 및 관리하고, 작업 환경에 연결한 다음, Cloud Backup Service를 사용하여 영구 볼륨을 백업할 수 있습니다. Cloud Manager는 Trident 연산자를 사용하여 수동으로 또는 Helm을 사용하여 Astra Trident 구축을 지원합니다.



=== Helm을 사용해야 하는 이유는 무엇입니까?

Astra Trident 21.01부터 Helm을 사용하여 관리하는 다른 애플리케이션이 있는 경우 Helm을 사용하여 배포를 관리할 수도 있습니다.



=== Tribidenctl은 언제 사용해야 합니까?

업그레이드해야 하는 기존 배포가 있거나 배포를 고도로 사용자 지정하려는 경우 를 사용하는 방법을 고려해야 합니다 link:kubernetes-deploy-tridentctl.html["tridentctl 을 선택합니다"^]. Astra Trident를 구축하는 기존 방법입니다.



== 배포 방법 간에 이동할 때의 고려 사항

배포 방법 간에 이동해야 하는 시나리오를 상상하기란 쉽지 않습니다. 에서 이동하기 전에 다음 사항을 고려해야 합니다 `tridentctl` 연산자 기반 배포로 배포하거나 그 반대로 배포:

* Astra Trident를 제거할 때는 항상 동일한 방법을 사용하십시오. 을(를) 배포한 경우 `tridentctl`, 의 해당 버전을 사용해야 합니다 `tridentctl` Astra Trident를 제거하는 바이너리. 마찬가지로 연산자를 사용하여 를 배포하는 경우에는 를 편집해야 합니다 `TridentOrchestrator` CR 및 SET `spec.uninstall=true` Astra Trident를 제거합니다.
* 를 제거하고 사용할 운영자 기반 배포가 있는 경우 `tridentctl` Astra Trident를 배포하려면 먼저 편집해야 합니다 `TridentOrchestrator` 그리고 설정합니다 `spec.uninstall=true` Astra Trident를 제거합니다. 그런 다음 삭제합니다 `TridentOrchestrator` 및 작업자 배포. 그런 다음 를 사용하여 를 설치할 수 있습니다 `tridentctl`.
* 작업자 기반의 수동 배포를 사용하고 H제어 기반 Trident 연산자 배포를 사용하려는 경우 먼저 수동으로 연산자를 제거한 다음 Helm 설치를 수행해야 합니다. 이를 통해 Helm은 필요한 레이블 및 주석을 사용하여 Trident 연산자를 배포할 수 있습니다. 이렇게 하지 않으면 레이블 유효성 검사 오류 및 주석 유효성 검사 오류와 함께 H제어 기반 Trident 연산자 배포가 실패합니다. 가 있는 경우 `tridentctl`기반 배포에서는 문제 없이 Helm 기반 배포를 사용할 수 있습니다.




== 배포 모드를 이해합니다

Astra Trident를 구축하는 방법에는 세 가지가 있습니다.



=== Standard 구축

Kubernetes 클러스터에서 Trident를 구축하면 Astra Trident 설치 관리자가 다음 두 가지 작업을 수행할 수 있습니다.

* 인터넷을 통해 컨테이너 이미지를 가져오는 중입니다
* Kubernetes 클러스터의 모든 유효한 노드에서 Astra Trident Pod를 가동하는 구축 및/또는 노드 데모 생성


이와 같은 표준 배포는 두 가지 방법으로 수행할 수 있습니다.

* 사용 `tridentctl install`
* Trident 연산자 사용 Trident 연산자는 수동으로 또는 Helm을 사용하여 배포할 수 있습니다.


이 설치 모드는 Astra Trident를 설치하는 가장 쉬운 방법이며 네트워크 제한이 없는 대부분의 환경에서 작동합니다.



=== 오프라인 배포

공기 Gapped 배포를 수행하려면 를 사용합니다 `--image-registry` 호출 시 플래그 `tridentctl install` 개인 이미지 레지스트리를 가리킵니다. Trident 연산자를 사용하여 배포하는 경우 또는 을 지정할 수 있습니다 `spec.imageRegistry` 을 클릭합니다 `TridentOrchestrator`. 이 레지스트리에는 가 포함되어 있어야 합니다 https://hub.docker.com/r/netapp/trident/["Trident 이미지"^], https://hub.docker.com/r/netapp/trident-autosupport/["Trident AutoSupport 이미지"^]및 Kubernetes 버전에서 요구하는 CSI 사이드카 이미지를 참조하십시오.

를 사용하여 배포를 사용자 지정할 수 있습니다 `tridentctl` Trident의 리소스에 대한 매니페스트를 생성합니다. 여기에는 구축, 개발/제거, 서비스 계정, Astra Trident가 설치의 일부로 생성한 클러스터 역할 등이 포함됩니다.

배포 사용자 지정에 대한 자세한 내용은 다음 링크를 참조하십시오.

* link:kubernetes-customize-deploy.html["운영자 기반 배포를 사용자 지정합니다"^]
* 



IMPORTANT: 개인 이미지 리포지토리를 사용하는 경우 를 추가해야 합니다 `/sig-storage` 개인 레지스트리 URL의 끝까지. 에 대한 개인 레지스트리를 사용하는 경우 `tridentctl` 배포는 을 사용해야 합니다 `--trident-image` 및 `--autosupport-image` 와 함께 제공됩니다 `--image-registry`. Trident 연산자를 사용하여 Astra Trident를 배포하는 경우 Orchestrator CR에 포함되어 있는지 확인합니다 `tridentImage` 및 `autosupportImage` 를 입력합니다.



=== 원격 배포

다음은 원격 배포 프로세스에 대한 상위 수준의 개요입니다.

* 적절한 버전의 를 배포합니다 `kubectl` Astra Trident를 구축하려는 원격 머신
* Kubernetes 클러스터에서 구성 파일을 복사하고 를 설정합니다 `KUBECONFIG` 원격 시스템의 환경 변수.
* 를 시작합니다 `kubectl get nodes` 명령을 실행하여 필요한 Kubernetes 클러스터에 연결할 수 있는지 확인하십시오.
* 표준 설치 단계를 사용하여 원격 컴퓨터에서 배포를 완료합니다.




== 기타 알려진 구성 옵션

VMware Tanzu 포트폴리오 제품에 Astra Trident를 설치할 경우:

* 클러스터는 권한이 있는 워크로드를 지원해야 합니다.
* 를 클릭합니다 `--kubelet-dir` 플래그를 kubelet 디렉터리의 위치로 설정해야 합니다. 기본적으로 이 값은 입니다 `/var/vcap/data/kubelet`.
+
를 사용하여 kubelet 위치 지정 `--kubelet-dir` Trident Operator, Helm 및 에 대해 작업하는 것으로 알려져 있습니다 `tridentctl` 적합합니다.


