---
sidebar: sidebar 
permalink: trident-reference/trident-cl.html 
keywords: command-line, options, logging, kubernetes, docker, ports 
summary: Astra Trident는 Trident Orchestrator를 위한 여러 명령줄 옵션을 공개하고 특정 포트를 통해 통신합니다. 
---
= 명령줄 옵션
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident는 Trident Orchestrator를 위한 여러 명령줄 옵션을 제공합니다. 이러한 옵션을 사용하여 배포를 수정할 수 있습니다.



== 로깅

* `-debug`: 디버깅 출력을 활성화합니다.
* `-loglevel <level>`: 로깅 수준을 설정합니다(debug, info, warn, error, fatal). 기본적으로 info(정보) 가 사용됩니다.




== 쿠버네티스

* `-k8s_pod`: 이 옵션 또는 을 사용합니다 `-k8s_api_server` Kubernetes 지원을 사용하도록 설정하십시오. 이 설정을 사용하면 Trident에서 포함된 POD의 Kubernetes 서비스 계정 자격 증명을 사용하여 API 서버에 연락합니다. Trident가 서비스 계정이 활성화된 Kubernetes 클러스터에서 POD로 실행되는 경우에만 작동합니다.
* `-k8s_api_server <insecure-address:insecure-port>`: 이 옵션 또는 을 사용합니다 `-k8s_pod` Kubernetes 지원을 사용하도록 설정하십시오. Trident가 지정된 경우 제공된 비보안 주소 및 포트를 사용하여 Kubernetes API 서버에 연결합니다. 따라서 Trident를 POD 외부에 배포할 수 있지만 API 서버에 대한 비보안 연결만 지원합니다. 를 사용하여 포드에 Trident를 배포하여 안전하게 연결합니다 `-k8s_pod` 옵션을 선택합니다.
* `-k8s_config_path <file>`: 필수. KubeConfig 파일에 대한 이 경로를 지정해야 합니다.




== Docker 를 참조하십시오

* `-volume_driver <name>`: Docker 플러그인을 등록할 때 사용되는 드라이버 이름입니다. 기본값은 입니다 `netapp`.
* `-driver_port <port-number>`: UNIX 도메인 소켓이 아닌 이 포트에서 수신 대기하십시오.
* `-config <file>`필수: 백엔드 구성 파일에 대한 이 경로를 지정해야 합니다.




== 휴식

* `-address <ip-or-host>`: Trident의 REST 서버가 수신할 주소를 지정합니다. 기본값은 localhost입니다. localhost에서 듣거나 Kubernetes Pod에서 실행 중인 경우, REST 인터페이스는 Pod 외부에서 직접 액세스할 수 없습니다. 사용 `-address ""` REST 인터페이스를 POD IP 주소에서 액세스할 수 있도록 합니다.



CAUTION: Trident REST 인터페이스는 127.0.0.1(IPv4의 경우) 또는 [::1](IPv6의 경우)에서만 수신 및 서비스하도록 구성할 수 있습니다.

* `-port <port-number>`: Trident의 REST 서버가 수신할 포트를 지정합니다. 기본값은 8000입니다.
* `-rest`: REST 인터페이스를 활성화합니다. 기본값은 true 입니다.

